suppressPackageStartupMessages({library(GEOquery); library(limma); library(data.table); library(msigdbr); library(dorothea)})
set.seed(20261005)
gse <- getGEO(filename = "GSE40564_series_matrix.txt.gz", getGPL = FALSE); e <- exprs(gse)
ann <- fread("GPL570.annot.gz", skip = "ID\tGene title", fill = TRUE, sep = "\t", quote = ""); symOf <- setNames(ann[["Gene symbol"]], ann$ID)
s <- symOf[rownames(e)]; k <- !grepl("^AFFX", rownames(e)) & !is.na(s) & s != "" & !grepl("///", s, fixed = TRUE)
e <- e[k, ]; e <- e[rowSums(e > quantile(e, .25)) >= 3, ]; s <- symOf[rownames(e)]; o <- order(s, -rowMeans(e)); f <- !duplicated(s[o]); g <- e[o[f], ]; rownames(g) <- s[o[f]]
grp <- factor(rep(c("DMSO","PIK75","TGX221"), each = 3)); design <- model.matrix(~0 + grp); colnames(design) <- levels(grp)
cm <- makeContrasts(PIK = PIK75 - DMSO, TGX = TGX221 - DMSO, levels = design)
cat("=== POINT 4: does mroast saturate? random gene sets\n")
for (n in c(25, 100, 190)) { idx <- replicate(300, sample(nrow(g), n), simplify = FALSE); names(idx) <- paste0("r", 1:300)
  r1 <- mroast(g, idx, design, contrast = cm[, "PIK"], nrot = 1999); r2 <- mroast(g, idx, design, contrast = cm[, "TGX"], nrot = 1999)
  cat(sprintf("random sets of %3d genes: PIK-75 %.0f%% with p<0.05 (%.0f%% FDR<0.05); TGX-221 %.0f%% with p<0.05\n", n, 100*mean(r1$PValue < .05), 100*mean(r1$FDR < .05), 100*mean(r2$PValue < .05))) }
H <- msigdbr(species = "Homo sapiens", collection = "H"); RE <- msigdbr(species = "Homo sapiens", collection = "C2", subcollection = "CP:REACTOME")
L <- c(split(H$gene_symbol, H$gs_name), split(RE$gene_symbol, RE$gs_name))
focus <- c("HALLMARK_UNFOLDED_PROTEIN_RESPONSE","HALLMARK_MTORC1_SIGNALING","HALLMARK_CHOLESTEROL_HOMEOSTASIS","HALLMARK_HYPOXIA","HALLMARK_GLYCOLYSIS","HALLMARK_E2F_TARGETS","HALLMARK_G2M_CHECKPOINT","HALLMARK_PI3K_AKT_MTOR_SIGNALING","HALLMARK_DNA_REPAIR","HALLMARK_MYC_TARGETS_V1","REACTOME_EUKARYOTIC_TRANSLATION_INITIATION","REACTOME_RESPONSE_OF_EIF2AK4_GCN2_TO_AMINO_ACID_DEFICIENCY","REACTOME_CHOLESTEROL_BIOSYNTHESIS","REACTOME_HOMOLOGY_DIRECTED_REPAIR","REACTOME_ATF4_ACTIVATES_GENES_IN_RESPONSE_TO_ENDOPLASMIC_RETICULUM_STRESS")
idx <- ids2indices(L[focus], rownames(g))
cat("\ncamera (competitive test that allows for inter-gene correlation):\n")
c1 <- camera(g, idx, design, contrast = cm[, "PIK"]); c2 <- camera(g, idx, design, contrast = cm[, "TGX"])
out <- data.frame(set = substr(sub("HALLMARK_|REACTOME_", "", rownames(c1)), 1, 40), PIK_dir = c1$Direction, PIK_FDR = signif(c1$FDR, 2), TGX_dir = c2[rownames(c1), "Direction"], TGX_FDR = signif(c2[rownames(c1), "FDR"], 2)); print(out, row.names = FALSE)
cat("\n=== POINT 6: SREBF regulons vs Table 2 genes\n")
data(dorothea_hs, package = "dorothea"); nt <- subset(dorothea_hs, confidence %in% c("A","B","C"))
t2 <- c("SQLE","HMGCS1","HMGCR","LDLR","SCD","LSS","FDFT1","ACACA","INSIG1","FASN")
for (tf in c("SREBF1","SREBF2")) { tg <- intersect(nt$target[nt$tf == tf], rownames(g)); cat(tf, "regulon:", length(tg), "targets in data;", length(intersect(tg, t2)), "of the 10 Table 2 SREBP genes are in it:", paste(intersect(tg, t2), collapse = ", "), "\n") }
cat("\n=== POINT 8: subtype vs neuroendocrine score in UCologne\n")
cc <- readRDS("ext/ucologne_expr.rds"); X <- cc$X; X <- X[apply(X, 1, sd, na.rm = TRUE) > 0 & rowMeans(is.na(X)) == 0, ]; Z <- t(scale(t(X)))
de <- fread("results/Table_S1_DE_PIK75_vs_DMSO.csv"); dn <- intersect(de[adj.P.Val < .05 & logFC <= -1, gene], rownames(Z)); up <- intersect(de[adj.P.Val < .05 & logFC >= 1, gene], rownames(Z))
prog <- colMeans(Z[dn, ]) - colMeans(Z[up, ])
NEpos <- c("BEX1","ASCL1","INSM1","CHGA","TAGLN3","KIF5C","CRMP1","SCG3","SYT4","RTN1","MYT1L","SYP","KIF1A","TMSB15A","SYN1","SYT11","RUNDC3A","TFF3","CHGB","FAM57B","SH3GL2","BSN","SEZ6","TMSB15B","CELF3")
NEneg <- c("RAB27B","TGFBR2","SLC16A5","S100A10","ITGB4","YAP1","LGALS3","EPHA2","S100A16","PLAU","ABCC3","ARHGDIB","CYR61","PTGES","CCND1","IFITM2","IFITM3","AHNAK","CAV2","TACSTD2","TGFBI","EMP1","CAV1","ANXA1","MYOF")
NE <- colMeans(Z[intersect(NEpos, rownames(Z)), ]) - colMeans(Z[intersect(NEneg, rownames(Z)), ])
mk <- c(A = "ASCL1", N = "NEUROD1", P = "POU2F3", Y = "YAP1"); sub <- factor(names(mk)[apply(Z[mk, ], 2, which.max)])
print(data.table(subtype = sub, prog = prog, NE = NE)[, .(n = .N, median_programme = round(median(prog), 2), median_NE = round(median(NE), 2), NE_min = round(min(NE), 2), NE_max = round(max(NE), 2)), by = subtype][order(subtype)])
cat(sprintf("NE score by subtype: Kruskal-Wallis p = %.2g\n", kruskal.test(NE ~ sub)$p.value))
cat("Spearman rho of programme score with: ", paste(sprintf("%s %.2f", mk, sapply(mk, function(m) cor(prog, Z[m, ], method = "spearman"))), collapse = "; "), sprintf("; NE-positive genes only %.2f; non-NE genes only %.2f\n", cor(prog, colMeans(Z[intersect(NEpos, rownames(Z)), ]), method = "spearman"), cor(prog, colMeans(Z[intersect(NEneg, rownames(Z)), ]), method = "spearman")))
cat(sprintf("Tumours where the top marker z-score is < 0.5 (weak call): %d of 81\n", sum(apply(Z[mk, ], 2, max) < 0.5)))
cat(sprintf("Programme score within NE-high half vs NE-low half: median %.2f vs %.2f\n", median(prog[NE > median(NE)]), median(prog[NE <= median(NE)])))
cat(sprintf("Programme ~ subtype after removing POU2F3 group: KW p = %.3f; A+N vs P+Y Wilcoxon p = %.4f\n", kruskal.test(prog[sub != "P"] ~ droplevels(sub[sub != "P"]))$p.value, wilcox.test(prog[sub %in% c("A","N")], prog[!(sub %in% c("A","N"))])$p.value))
for (s in levels(sub)) cat(sprintf("within SCLC-%s: rho(programme, NE) = %.2f (n=%d)\n", s, cor(prog[sub==s], NE[sub==s], method="spearman"), sum(sub==s)))
